-- One-time import of Google Drive posts + stats (generated by build-import.mjs).
-- Clears ALL content (accounts/campaigns/posts/stats) — users and roles stay.
-- Run as postgres (Supabase Studio SQL editor or psql); RLS does not apply there.

begin;

delete from public.accounts;

insert into public.accounts (id, user_id, platform, display_name, linkedin_url)
values ('acdf806f-96f9-48d1-adf2-e1358b529d7e', (select id from public.users order by created_at asc limit 1), 'linkedin', 'Mykyta Business', 'https://www.linkedin.com/in/mykyta-shevchenko-ciphercross-wellness/');
insert into public.campaigns (id, account_id, title, description, status)
values ('70fd6c98-17f2-4e56-be6c-cea7055fb759', 'acdf806f-96f9-48d1-adf2-e1358b529d7e', 'LinkedIn 2026', 'Imported from the Google Drive content plan & stats sheet.', 'active');

insert into public.accounts (id, user_id, platform, display_name, linkedin_url)
values ('a3edf6c7-e1a2-40af-a617-4efc551ccd66', (select id from public.users order by created_at asc limit 1), 'linkedin', 'Mykyta Personal', 'https://www.linkedin.com/in/mykyta-shevchenko-ciphercross/');
insert into public.campaigns (id, account_id, title, description, status)
values ('002dc3bc-983b-4153-9759-6fd8e6200887', 'a3edf6c7-e1a2-40af-a617-4efc551ccd66', 'LinkedIn 2026', 'Imported from the Google Drive content plan & stats sheet.', 'active');

insert into public.accounts (id, user_id, platform, display_name, linkedin_url)
values ('4b6efeb8-8f3c-43de-bdab-d4a44c71596c', (select id from public.users order by created_at asc limit 1), 'linkedin', 'CipherCross Company Page', null);
insert into public.campaigns (id, account_id, title, description, status)
values ('7457514f-ff06-4512-8726-3b980ef6e90f', '4b6efeb8-8f3c-43de-bdab-d4a44c71596c', 'LinkedIn 2026', 'Imported from the Google Drive content plan & stats sheet.', 'active');

insert into public.posts (id, campaign_id, theme, position, body, linkedin_url, status, scheduled_at, posted_at)
values ('b9b22896-8d5f-4ca5-939a-6d04c112efe3', '70fd6c98-17f2-4e56-be6c-cea7055fb759', 'Self-doubt gets a bad reputation. In leadership, in startups', 0, 'Self-doubt gets a bad reputation. In leadership, in startups, in decision-making - it’s usually labeled as a flaw.

But over the past year, I’ve realized that if you recognize it and apply it wisely, self-doubt can actually be a strength.

Here’s how I use it:

1) Double-checking solutions: “What if there’s a better approach?” or “Did I miss something?”
2) Polishing outcomes: Re-examining decisions often leads to stronger results.
3) Mindful application: The key is awareness - don’t overthink, but don’t ignore your doubts.

In running a wellness tech startup, every small improvement matters.
Self-doubt, when controlled, is not paralysis.

It’s a tool that helps me build better solutions for our users and strengthen our processes at CipherCross.

Leadership isn’t about never doubting yourself.
It’s about using your doubts to fuel better decisions.

ð¡How do you turn challenges or doubts into an advantage in your work?

<https://www.figma.com/design/ghrgcaInRycN4UJ29mgRUJ/Mykyta--1--Posts?node-id=0-1&t=rETsVPNqngMJsUY8-1>', 'https://www.linkedin.com/posts/mykyta-shevchenko-ciphercross-wellness_self-doubt-gets-a-bad-reputation-in-leadership-activity-7440298559100522496-ECKf?utm_source=share&utm_medium=member_desktop&rcm=ACoAACKi8XsB9WBoWK1z6g7nRgrBaW3-4QoyJT8', 'posted', '2026-03-19T09:00:00Z', '2026-03-19T09:00:00Z');
insert into public.post_stats (post_id, views, likes, comments, recorded_at)
values ('b9b22896-8d5f-4ca5-939a-6d04c112efe3', 154, 3, 0, '2026-06-02T12:00:00Z');
insert into public.posts (id, campaign_id, theme, position, body, linkedin_url, status, scheduled_at, posted_at)
values ('ca0c13ba-d841-49e5-ad3a-e3bd49daae17', '70fd6c98-17f2-4e56-be6c-cea7055fb759', 'A few months ago, our support team started noticing a recurr', 1, 'A few months ago, our support team started noticing a recurring issue on our platform that helps small, local businesses manage their bookings:

Vendors were getting bookings at completely wrong times. A pottery class in Lisbon could receive a booking for 2 AM. A small workshop host might get a customer arriving at the wrong time.
For vendors who are just starting on our platform, it was confusing, frustrating, and created negative first impressions. Support tickets were piling up, and I realized this small problem was affecting trust in our system.

My first instinct was to redesign the entire scheduling system.
I imagined a big project: new tutorials, redesigning pages, maybe even rethinking the architecture. But before diving into something complex, I decided to approach it differently - I went through the sign-up process myself, exactly as a new user would.

And then I found it.

The culprit was a tiny detail: the time zone field defaulted to UTC. To a developer, that’s logical - a universal standard. But for a local vendor in Lisbon, it made no sense. They would enter "9:00 AM" assuming it was local time, but the system registered it as 9:00 AM UTC. During daylight saving periods, the timing could be even more off.

So the solution?
Small, simple, and elegant.
We wrote a script to detect the user’s browser time zone automatically and pre-select it in the dropdown. Users could still change it if needed, but for 99% of them, it just worked. One developer implemented it in about 30 minutes.

The impact was immediate:

1) Support tickets related to scheduling errors dropped by over 90%.
2) Vendors felt that the platform finally “just worked.”
3) Trust and user confidence increased dramatically.

This experience reminded me of a powerful lesson: sometimes the biggest impact comes not from adding a new feature, but from removing a tiny obstacle that your users don’t even realize is there.

It also reinforced our company philosophy at CipherCross: always meet users where they are.
Build systems that feel intuitive, that reduce friction, and that focus on the human experience behind every interaction.

Small details matter. They build trust, reduce frustration, and can transform user experience - sometimes more than any flashy feature ever could.

ð¡ What small change in your product, process, or service has made a huge difference for your users?

<https://www.figma.com/design/ghrgcaInRycN4UJ29mgRUJ/Mykyta--1--Posts?node-id=0-1&t=rETsVPNqngMJsUY8-1>', 'https://www.linkedin.com/posts/mykyta-shevchenko-ciphercross-wellness_a-few-months-ago-our-support-team-started-activity-7441744321499877376-NaJk?utm_source=share&utm_medium=member_desktop&rcm=ACoAACKi8XsB9WBoWK1z6g7nRgrBaW3-4QoyJT8', 'posted', '2026-03-23T09:00:00Z', '2026-03-23T09:00:00Z');
insert into public.post_stats (post_id, views, likes, comments, recorded_at)
values ('ca0c13ba-d841-49e5-ad3a-e3bd49daae17', 90, 1, 0, '2026-06-02T12:00:00Z');
insert into public.posts (id, campaign_id, theme, position, body, linkedin_url, status, scheduled_at, posted_at)
values ('9f613b6e-1e0b-4bad-b222-81fac291565f', '70fd6c98-17f2-4e56-be6c-cea7055fb759', 'Leadership strategy wellness', 2, '', 'https://www.linkedin.com/posts/mykyta-shevchenko-ciphercross-wellness_leadership-strategy-wellness-activity-7442480422464253952-bu4R?utm_source=share&utm_medium=member_desktop&rcm=ACoAACKi8XsB9WBoWK1z6g7nRgrBaW3-4QoyJT8', 'posted', '2026-03-25T09:00:00Z', '2026-03-25T09:00:00Z');
insert into public.post_stats (post_id, views, likes, comments, recorded_at)
values ('9f613b6e-1e0b-4bad-b222-81fac291565f', 74, 1, 0, '2026-06-02T12:00:00Z');
insert into public.posts (id, campaign_id, theme, position, body, linkedin_url, status, scheduled_at, posted_at)
values ('719adbec-53cc-4834-b83a-99dae3b24e86', '70fd6c98-17f2-4e56-be6c-cea7055fb759', 'I’ve noticed something in both business and life:', 3, 'I’ve noticed something in both business and life:
We love quick fixes.
A single retreat.
One therapy session.
A motivational quote.

But real mental health doesn’t come from shortcuts.
It’s not a sprint - it’s a marathon.

For me, the difference became clear when I finally allowed myself to rest after years of nonstop work.
I realized that recharging isn’t about one moment - it’s about building long-term systems that support you consistently.

Sometimes that system is a 3–5 hour hike in nature, where ideas start flowing and my mind clears.
Other times, it’s something small, like giving myself permission to celebrate a task with a treat or even 30 minutes of Instagram scrolling.

It’s not about the length of the activity - it’s about recognizing what your mind and body need at that moment.

At CipherCross, this is also how we approach wellness technology: not as a one-off “solution,” but as an ongoing journey.
Systems, habits, and supportive structures matter far more than quick wins.

Mental health is not a checkbox.
It’s a practice you commit to every day.

What does your “marathon” of mental health look like?

<https://drive.google.com/file/d/1mp5ErKiP1FdMe6PWsooPZriMg8A-KHE9/view?usp=sharing>', 'https://www.linkedin.com/posts/mykyta-shevchenko-ciphercross-wellness_ive-noticed-something-in-both-business-and-activity-7442835255415390208-b3mZ?utm_source=share&utm_medium=member_desktop&rcm=ACoAACKi8XsB9WBoWK1z6g7nRgrBaW3-4QoyJT8', 'posted', '2026-03-26T09:00:00Z', '2026-03-26T09:00:00Z');
insert into public.post_stats (post_id, views, likes, comments, recorded_at)
values ('719adbec-53cc-4834-b83a-99dae3b24e86', 91, 2, 0, '2026-06-02T12:00:00Z');
insert into public.posts (id, campaign_id, theme, position, body, linkedin_url, status, scheduled_at, posted_at)
values ('de9e58ff-a35f-4065-9ca6-ca71a3e18799', '70fd6c98-17f2-4e56-be6c-cea7055fb759', 'Many people tie ambition to money.', 4, 'Many people tie ambition to money.
The idea is: if you want to succeed, you need to stay hungry - for wealth, titles, recognition.

But I’ve learned that this kind of hunger rarely leads to fulfillment.

The mindset that has brought me the most growth - in business and in life - is different: staying hungry for experiences.

Because life is not a straight line toward a bank account balance.
It’s a mosaic of moments, challenges, lessons, and perspectives.

For me, this means:

→ Saying yes to new adventures, even when they’re outside my comfort zone.
→ Approaching cultures, people, and ideas with curiosity instead of judgment.
→ Treating every experience as a way to expand not just my knowledge, but my empathy.

This mindset directly shapes how we build at CipherCross, too.

Creating wellness apps isn’t just about scaling technology - it’s about embracing the multipolarity of human lives, meeting people where they are, and learning from every interaction.

When you stay hungry for experiences, you stop chasing growth just in numbers.
You start creating growth that actually matters.

ð¡ What are you currently “hungry” for - money, recognition, or experiences?

no photo, because it is “reflection” post', 'https://www.linkedin.com/posts/mykyta-shevchenko-ciphercross-wellness_many-people-tie-ambition-to-money-the-idea-activity-7444262151915028480-6Jnw?utm_source=share&utm_medium=member_desktop&rcm=ACoAACKi8XsB9WBoWK1z6g7nRgrBaW3-4QoyJT8', 'posted', '2026-03-30T09:00:00Z', '2026-03-30T09:00:00Z');
insert into public.post_stats (post_id, views, likes, comments, recorded_at)
values ('de9e58ff-a35f-4065-9ca6-ca71a3e18799', 215, 1, 0, '2026-06-02T12:00:00Z');
insert into public.posts (id, campaign_id, theme, position, body, linkedin_url, status, scheduled_at, posted_at)
values ('6f69eb76-5222-496b-aac1-e0c91d39a050', '70fd6c98-17f2-4e56-be6c-cea7055fb759', 'Wellnesstech userexperience empathyindesign', 5, '', 'https://www.linkedin.com/posts/mykyta-shevchenko-ciphercross-wellness_wellnesstech-userexperience-empathyindesign-activity-7445009680617312256-dpWm?utm_source=share&utm_medium=member_desktop&rcm=ACoAACKi8XsB9WBoWK1z6g7nRgrBaW3-4QoyJT8', 'posted', '2026-04-01T09:00:00Z', '2026-04-01T09:00:00Z');
insert into public.post_stats (post_id, views, likes, comments, recorded_at)
values ('6f69eb76-5222-496b-aac1-e0c91d39a050', 100, 1, 0, '2026-06-02T12:00:00Z');
insert into public.posts (id, campaign_id, theme, position, body, linkedin_url, status, scheduled_at, posted_at)
values ('69439220-db2a-4d6c-94a0-7d205e9f9c2f', '70fd6c98-17f2-4e56-be6c-cea7055fb759', 'Partnership leadership wellnesstech', 6, '', 'https://www.linkedin.com/posts/mykyta-shevchenko-ciphercross-wellness_partnership-leadership-wellnesstech-activity-7445364456056066048-0e9l?utm_source=share&utm_medium=member_desktop&rcm=ACoAACKi8XsB9WBoWK1z6g7nRgrBaW3-4QoyJT8', 'posted', '2026-04-02T09:00:00Z', '2026-04-02T09:00:00Z');
insert into public.post_stats (post_id, views, likes, comments, recorded_at)
values ('69439220-db2a-4d6c-94a0-7d205e9f9c2f', 253, 4, 2, '2026-06-02T12:00:00Z');
insert into public.posts (id, campaign_id, theme, position, body, linkedin_url, status, scheduled_at, posted_at)
values ('9d1daf98-69f3-4473-a2d3-77e0abe13219', '70fd6c98-17f2-4e56-be6c-cea7055fb759', 'Leadership wellness entrepreneurship', 7, '', 'https://www.linkedin.com/posts/mykyta-shevchenko-ciphercross-wellness_leadership-wellness-entrepreneurship-activity-7446806438100000768-T-xF?utm_source=share&utm_medium=member_desktop&rcm=ACoAACKi8XsB9WBoWK1z6g7nRgrBaW3-4QoyJT8', 'posted', '2026-04-06T09:00:00Z', '2026-04-06T09:00:00Z');
insert into public.post_stats (post_id, views, likes, comments, recorded_at)
values ('9d1daf98-69f3-4473-a2d3-77e0abe13219', 95, 4, 0, '2026-06-02T12:00:00Z');
insert into public.posts (id, campaign_id, theme, position, body, linkedin_url, status, scheduled_at, posted_at)
values ('064c46fe-d062-4cd7-9bcc-2fd353845138', '70fd6c98-17f2-4e56-be6c-cea7055fb759', 'The best business habit ive built this year', 8, '', 'https://www.linkedin.com/posts/mykyta-shevchenko-ciphercross-wellness_the-best-business-habit-ive-built-this-year-activity-7447180118063681536-md7x?utm_source=share&utm_medium=member_desktop&rcm=ACoAACKi8XsB9WBoWK1z6g7nRgrBaW3-4QoyJT8', 'posted', '2026-04-07T09:00:00Z', '2026-04-07T09:00:00Z');
insert into public.post_stats (post_id, views, likes, comments, recorded_at)
values ('064c46fe-d062-4cd7-9bcc-2fd353845138', 120, 7, 2, '2026-06-02T12:00:00Z');
insert into public.posts (id, campaign_id, theme, position, body, linkedin_url, status, scheduled_at, posted_at)
values ('a74956f4-2ee2-40fb-9b6a-60a007ac1ad0', '70fd6c98-17f2-4e56-be6c-cea7055fb759', 'The diary of a ceo the 33 laws of business', 9, '', 'https://www.linkedin.com/posts/mykyta-shevchenko-ciphercross-wellness_the-diary-of-a-ceo-the-33-laws-of-business-activity-7447882299687288833-r0La?utm_source=share&utm_medium=member_desktop&rcm=ACoAACKi8XsB9WBoWK1z6g7nRgrBaW3-4QoyJT8', 'posted', '2026-04-09T09:00:00Z', '2026-04-09T09:00:00Z');
insert into public.post_stats (post_id, views, likes, comments, recorded_at)
values ('a74956f4-2ee2-40fb-9b6a-60a007ac1ad0', 81, 4, 0, '2026-06-02T12:00:00Z');
insert into public.posts (id, campaign_id, theme, position, body, linkedin_url, status, scheduled_at, posted_at)
values ('458414b2-6543-4e35-9eb1-6223ffb83b44', '70fd6c98-17f2-4e56-be6c-cea7055fb759', 'My notes app is chaotic random ideas', 10, '', 'https://www.linkedin.com/posts/mykyta-shevchenko-ciphercross-wellness_my-notes-app-is-chaotic-random-ideas-activity-7449335574303232000-1Fz2?utm_source=share&utm_medium=member_desktop&rcm=ACoAACKi8XsB9WBoWK1z6g7nRgrBaW3-4QoyJT8', 'posted', '2026-04-13T09:00:00Z', '2026-04-13T09:00:00Z');
insert into public.post_stats (post_id, views, likes, comments, recorded_at)
values ('458414b2-6543-4e35-9eb1-6223ffb83b44', 115, 3, 0, '2026-06-02T12:00:00Z');
insert into public.posts (id, campaign_id, theme, position, body, linkedin_url, status, scheduled_at, posted_at)
values ('1df09416-a370-446d-94a5-2392ad7a2b15', '70fd6c98-17f2-4e56-be6c-cea7055fb759', 'Theres a specific moment in product work', 11, '', 'https://www.linkedin.com/posts/mykyta-shevchenko-ciphercross-wellness_theres-a-specific-moment-in-product-work-activity-7449350714432090112-Z5Lt?utm_source=share&utm_medium=member_desktop&rcm=ACoAACKi8XsB9WBoWK1z6g7nRgrBaW3-4QoyJT8', 'posted', '2026-04-14T09:00:00Z', '2026-04-14T09:00:00Z');
insert into public.post_stats (post_id, views, likes, comments, recorded_at)
values ('1df09416-a370-446d-94a5-2392ad7a2b15', 96, 2, 0, '2026-06-02T12:00:00Z');
insert into public.posts (id, campaign_id, theme, position, body, linkedin_url, status, scheduled_at, posted_at)
values ('01c78d23-479a-4261-a63b-3fe3568ece0e', '70fd6c98-17f2-4e56-be6c-cea7055fb759', 'Sometimes my best strategic thinking happens', 12, '', 'https://www.linkedin.com/posts/mykyta-shevchenko-ciphercross-wellness_sometimes-my-best-strategic-thinking-happens-activity-7450434050823012352-wCPr?utm_source=share&utm_medium=member_desktop&rcm=ACoAACKi8XsB9WBoWK1z6g7nRgrBaW3-4QoyJT8', 'posted', '2026-04-16T09:00:00Z', '2026-04-16T09:00:00Z');
insert into public.post_stats (post_id, views, likes, comments, recorded_at)
values ('01c78d23-479a-4261-a63b-3fe3568ece0e', 183, 2, 0, '2026-06-02T12:00:00Z');
insert into public.posts (id, campaign_id, theme, position, body, linkedin_url, status, scheduled_at, posted_at)
values ('3bef88b7-be8f-4de6-a047-e96a0ac0fc40', '70fd6c98-17f2-4e56-be6c-cea7055fb759', 'Empathy is a new metric', 13, '', 'https://www.linkedin.com/posts/mykyta-shevchenko-ciphercross-wellness_empathy-is-a-new-metric-activity-7452253599889334272-g8A9?utm_source=share&utm_medium=member_desktop&rcm=ACoAACKi8XsB9WBoWK1z6g7nRgrBaW3-4QoyJT8', 'posted', '2026-04-21T09:00:00Z', '2026-04-21T09:00:00Z');
insert into public.post_stats (post_id, views, likes, comments, recorded_at)
values ('3bef88b7-be8f-4de6-a047-e96a0ac0fc40', 180, 3, 0, '2026-06-02T12:00:00Z');
insert into public.posts (id, campaign_id, theme, position, body, linkedin_url, status, scheduled_at, posted_at)
values ('f479bd55-9ade-415c-8bec-222399e2f1e4', '70fd6c98-17f2-4e56-be6c-cea7055fb759', 'A team that genuinely cares can move faster', 14, '', 'https://www.linkedin.com/posts/mykyta-shevchenko-ciphercross-wellness_a-team-that-genuinely-cares-can-move-faster-activity-7452736741339275265-IbkL?utm_source=share&utm_medium=member_desktop&rcm=ACoAACKi8XsB9WBoWK1z6g7nRgrBaW3-4QoyJT8', 'posted', '2026-04-22T09:00:00Z', '2026-04-22T09:00:00Z');
insert into public.post_stats (post_id, views, likes, comments, recorded_at)
values ('f479bd55-9ade-415c-8bec-222399e2f1e4', 88, 2, 0, '2026-06-02T12:00:00Z');
insert into public.posts (id, campaign_id, theme, position, body, linkedin_url, status, scheduled_at, posted_at)
values ('752bf508-4b3c-4fcc-b669-39d2e4ecd573', '70fd6c98-17f2-4e56-be6c-cea7055fb759', 'Trust in healthtech saas', 15, '', 'https://www.linkedin.com/posts/mykyta-shevchenko-ciphercross-wellness_trust-in-healthtech-saas-activity-7452963223231709184-4r0f?utm_source=share&utm_medium=member_desktop&rcm=ACoAACKi8XsB9WBoWK1z6g7nRgrBaW3-4QoyJT8', 'posted', '2026-04-23T09:00:00Z', '2026-04-23T09:00:00Z');
insert into public.post_stats (post_id, views, likes, comments, recorded_at)
values ('752bf508-4b3c-4fcc-b669-39d2e4ecd573', 101, 1, 0, '2026-06-02T12:00:00Z');
insert into public.posts (id, campaign_id, theme, position, body, linkedin_url, status, scheduled_at, posted_at)
values ('99df1fd9-9f9c-4ecc-8dcb-cc8383d319f0', '70fd6c98-17f2-4e56-be6c-cea7055fb759', 'What users actually want from wellness apps', 16, '', 'https://www.linkedin.com/posts/mykyta-shevchenko-ciphercross-wellness_what-users-actually-want-from-wellness-apps-activity-7454778941275430913-bomH?utm_source=share&utm_medium=member_desktop&rcm=ACoAACKi8XsB9WBoWK1z6g7nRgrBaW3-4QoyJT8', 'posted', '2026-04-28T09:00:00Z', '2026-04-28T09:00:00Z');
insert into public.post_stats (post_id, views, likes, comments, recorded_at)
values ('99df1fd9-9f9c-4ecc-8dcb-cc8383d319f0', 133, 2, 0, '2026-06-02T12:00:00Z');
insert into public.posts (id, campaign_id, theme, position, body, linkedin_url, status, scheduled_at, posted_at)
values ('781bc31c-eaa2-4a2a-af1a-4d2948c0b708', '70fd6c98-17f2-4e56-be6c-cea7055fb759', 'Culture isnt defined in decks or mission', 17, '', 'https://www.linkedin.com/posts/mykyta-shevchenko-ciphercross-wellness_culture-isnt-defined-in-decks-or-mission-activity-7455152720233029632-QtYx?utm_source=share&utm_medium=member_desktop&rcm=ACoAACKi8XsB9WBoWK1z6g7nRgrBaW3-4QoyJT8', 'posted', '2026-04-29T09:00:00Z', '2026-04-29T09:00:00Z');
insert into public.post_stats (post_id, views, likes, comments, recorded_at)
values ('781bc31c-eaa2-4a2a-af1a-4d2948c0b708', 89, 0, 0, '2026-06-02T12:00:00Z');
insert into public.posts (id, campaign_id, theme, position, body, linkedin_url, status, scheduled_at, posted_at)
values ('d6c18ef9-fb49-4d35-81b3-79a6680c714d', '70fd6c98-17f2-4e56-be6c-cea7055fb759', 'Inmycorner case study', 18, '', 'https://www.linkedin.com/posts/mykyta-shevchenko-ciphercross-wellness_inmycorner-case-study-activity-7455496262864257024-_Fei?utm_source=share&utm_medium=member_desktop&rcm=ACoAACKi8XsB9WBoWK1z6g7nRgrBaW3-4QoyJT8', 'posted', '2026-04-30T09:00:00Z', '2026-04-30T09:00:00Z');
insert into public.post_stats (post_id, views, likes, comments, recorded_at)
values ('d6c18ef9-fb49-4d35-81b3-79a6680c714d', 125, 0, 0, '2026-06-02T12:00:00Z');
insert into public.posts (id, campaign_id, theme, position, body, linkedin_url, status, scheduled_at, posted_at)
values ('abaa6dfe-32b7-425d-a6f0-37db73400f9f', '002dc3bc-983b-4153-9759-6fd8e6200887', 'In wellness tech, collecting less data isn’t a weakness, it’', 0, 'In wellness tech, collecting less data isn’t a weakness, it’s a sign of respect.

We don’t need to know everything about a person to help them feel better.
However, many wellness apps behave similarly.

The problem?
They collect every heartbeat, sleep cycle, step count and emotion, just in case. But “collect it now, figure out later” is not innovation, but it is laziness and it erodes trust.

How we do it differently at CipherCross ð

→  Minimum viable data, nothing more. We only collect what’s essential to deliver value. If a feature doesn’t need raw heart rate or sleep depth, we don’t store it.

→  Consent should be obvious, not hidden. Users choose exactly what to sync: step count, heart rate, mood, etc. All via simple toggle-based flows. No dark patterns. No forced sharing.

→  Local-first logic wherever possible. Sensitive calculations (like stress scoring or mood prediction) stay on the user’s device. We only receive aggregated results, never raw signals.

→  Encryption by default. Access tokens and health data are encrypted at rest; no exceptions.

Why does this matter?

In digital health, trust is the new currency.
And trust isn’t built by collecting more data, it’s built by collecting less, but using it better.

Users don’t owe us their biometric lives. They allow us to borrow just enough to help and return it with care. If wellness tech wants to stay human, privacy is a foundation.

Curious how this works in real-life products? Happy to share more behind the scenes.

<https://www.figma.com/design/EqPMQ9lOTInKoZk4CQbeeM/Posts-Mykyta--2--Photo-Bali?node-id=0-1&t=jMJEAUxjLeh9bNc4-1>', 'https://www.linkedin.com/posts/mykyta-shevchenko-ciphercross_in-wellness-tech-collecting-less-data-isn-activity-7440333761055125504-xKyX?utm_source=share&utm_medium=member_desktop&rcm=ACoAAD1GaXQBLC3IwzuWDrLQoIsrw5Y1tC2y1Xs', 'posted', '2026-03-19T09:00:00Z', '2026-03-19T09:00:00Z');
insert into public.post_stats (post_id, views, likes, comments, recorded_at)
values ('abaa6dfe-32b7-425d-a6f0-37db73400f9f', 209, 7, 0, '2026-06-02T12:00:00Z');
insert into public.posts (id, campaign_id, theme, position, body, linkedin_url, status, scheduled_at, posted_at)
values ('59054127-0f02-4cae-a92f-a9f51235f0eb', '002dc3bc-983b-4153-9759-6fd8e6200887', 'When youre building a wellness focused company', 1, '', 'https://www.linkedin.com/posts/mykyta-shevchenko-ciphercross_when-youre-building-a-wellness-focused-company-activity-7441759408054927360-trau?utm_source=share&utm_medium=member_desktop&rcm=ACoAAD1GaXQBLC3IwzuWDrLQoIsrw5Y1tC2y1Xs', 'posted', '2026-03-23T09:00:00Z', '2026-03-23T09:00:00Z');
insert into public.post_stats (post_id, views, likes, comments, recorded_at)
values ('59054127-0f02-4cae-a92f-a9f51235f0eb', 194, 8, 0, '2026-06-02T12:00:00Z');
insert into public.posts (id, campaign_id, theme, position, body, linkedin_url, status, scheduled_at, posted_at)
values ('5c168a72-583c-4b94-9d65-6b7ace07d10f', '002dc3bc-983b-4153-9759-6fd8e6200887', 'Founderlife decisionmaking wellnesstech', 2, '', 'https://www.linkedin.com/posts/mykyta-shevchenko-ciphercross_founderlife-decisionmaking-wellnesstech-activity-7442476693019258880-QWbT?utm_source=share&utm_medium=member_desktop&rcm=ACoAAD1GaXQBLC3IwzuWDrLQoIsrw5Y1tC2y1Xs', 'posted', '2026-03-25T09:00:00Z', '2026-03-25T09:00:00Z');
insert into public.post_stats (post_id, views, likes, comments, recorded_at)
values ('5c168a72-583c-4b94-9d65-6b7ace07d10f', 218, 8, 0, '2026-06-02T12:00:00Z');
insert into public.posts (id, campaign_id, theme, position, body, linkedin_url, status, scheduled_at, posted_at)
values ('38e7ca41-c5be-4339-b7d8-c0ed25789dbb', '002dc3bc-983b-4153-9759-6fd8e6200887', 'The first thing i do in any new city find', 3, '', 'https://www.linkedin.com/posts/mykyta-shevchenko-ciphercross_the-first-thing-i-do-in-any-new-city-find-activity-7442846567696351232-raJC?utm_source=share&utm_medium=member_desktop&rcm=ACoAAD1GaXQBLC3IwzuWDrLQoIsrw5Y1tC2y1Xs', 'posted', '2026-03-26T09:00:00Z', '2026-03-26T09:00:00Z');
insert into public.post_stats (post_id, views, likes, comments, recorded_at)
values ('38e7ca41-c5be-4339-b7d8-c0ed25789dbb', 263, 8, 0, '2026-06-02T12:00:00Z');
insert into public.posts (id, campaign_id, theme, position, body, linkedin_url, status, scheduled_at, posted_at)
values ('6edd14d7-b62c-4f10-8611-b6a9957eca91', '002dc3bc-983b-4153-9759-6fd8e6200887', 'Deep focus', 4, '', 'https://www.linkedin.com/posts/mykyta-shevchenko-ciphercross_deep-focus-activity-7444273504960565248-_McY?utm_source=share&utm_medium=member_desktop&rcm=ACoAAD1GaXQBLC3IwzuWDrLQoIsrw5Y1tC2y1Xs', 'posted', '2026-03-30T09:00:00Z', '2026-03-30T09:00:00Z');
insert into public.post_stats (post_id, views, likes, comments, recorded_at)
values ('6edd14d7-b62c-4f10-8611-b6a9957eca91', 252, 6, 0, '2026-06-02T12:00:00Z');
insert into public.posts (id, campaign_id, theme, position, body, linkedin_url, status, scheduled_at, posted_at)
values ('23c36c0c-f9cb-4b8f-953f-3c6645b33e6c', '002dc3bc-983b-4153-9759-6fd8e6200887', 'Most wellness apps don’t fail because of poor UX, but users ', 5, 'Most wellness apps don’t fail because of poor UX, but users lose emotional connection.

Consistency isn’t just a behavior - it’s an emotion. Here’s how behavioral design helps users stay engaged and supported:

1️⃣ Emotional Mapping - Align flows with how users feel, not just what they want to achieve.
2️⃣ Micro-Accomplishments - Build momentum through small, meaningful wins.
3️⃣ Gentle Nudges - Encourage action without guilt or pressure.

At CipherCross, we design wellness experiences that understand human rhythm - balancing science, security and empathy. Because staying consistent starts with feeling understood.

ð¡ Most users don’t quit - they disconnect.

WellnessDesign #BehavioralUX #MentalHealthApps #CipherCross #ProductDesign #HealthTech

<https://www.figma.com/design/HVaLwFN5bmkQQlGsjtRZd0/Company-Page?node-id=2-53&t=7GYGo0oQIdDvjdIp-1>', 'https://www.linkedin.com/posts/mykyta-shevchenko-ciphercross_most-wellness-apps-dont-fail-because-of-activity-7445002568558075905-mnJC?utm_source=share&utm_medium=member_desktop&rcm=ACoAAD1GaXQBLC3IwzuWDrLQoIsrw5Y1tC2y1Xs', 'posted', '2026-04-01T09:00:00Z', '2026-04-01T09:00:00Z');
insert into public.post_stats (post_id, views, likes, comments, recorded_at)
values ('23c36c0c-f9cb-4b8f-953f-3c6645b33e6c', 460, 14, 2, '2026-06-02T12:00:00Z');
insert into public.posts (id, campaign_id, theme, position, body, linkedin_url, status, scheduled_at, posted_at)
values ('1c121499-7c3d-4f02-95f3-9f0e324c63f4', '002dc3bc-983b-4153-9759-6fd8e6200887', 'Building wellness products forces you to', 6, '', 'https://www.linkedin.com/posts/mykyta-shevchenko-ciphercross_building-wellness-products-forces-you-to-activity-7445371979286605825-vbkn?utm_source=share&utm_medium=member_desktop&rcm=ACoAAD1GaXQBLC3IwzuWDrLQoIsrw5Y1tC2y1Xs', 'posted', '2026-04-02T09:00:00Z', '2026-04-02T09:00:00Z');
insert into public.post_stats (post_id, views, likes, comments, recorded_at)
values ('1c121499-7c3d-4f02-95f3-9f0e324c63f4', 266, 10, 2, '2026-06-02T12:00:00Z');
insert into public.posts (id, campaign_id, theme, position, body, linkedin_url, status, scheduled_at, posted_at)
values ('e62bf4f3-158a-4cff-a355-5a5a89e685d8', '002dc3bc-983b-4153-9759-6fd8e6200887', 'One of our early ideas looked perfect on', 7, '', 'https://www.linkedin.com/posts/mykyta-shevchenko-ciphercross_one-of-our-early-ideas-looked-perfect-on-activity-7446806425177149440-K6FG?utm_source=share&utm_medium=member_desktop&rcm=ACoAAD1GaXQBLC3IwzuWDrLQoIsrw5Y1tC2y1Xs', 'posted', '2026-04-06T09:00:00Z', '2026-04-06T09:00:00Z');
insert into public.post_stats (post_id, views, likes, comments, recorded_at)
values ('e62bf4f3-158a-4cff-a355-5a5a89e685d8', 173, 8, 0, '2026-06-02T12:00:00Z');
insert into public.posts (id, campaign_id, theme, position, body, linkedin_url, status, scheduled_at, posted_at)
values ('32c43264-da01-4866-a0ba-d19afafe78f0', '002dc3bc-983b-4153-9759-6fd8e6200887', 'We once removed a feature we spent weeks', 8, '', 'https://www.linkedin.com/posts/mykyta-shevchenko-ciphercross_we-once-removed-a-feature-we-spent-weeks-activity-7447176389373505536-cWYc?utm_source=share&utm_medium=member_desktop&rcm=ACoAAD1GaXQBLC3IwzuWDrLQoIsrw5Y1tC2y1Xs', 'posted', '2026-04-07T09:00:00Z', '2026-04-07T09:00:00Z');
insert into public.post_stats (post_id, views, likes, comments, recorded_at)
values ('32c43264-da01-4866-a0ba-d19afafe78f0', 265, 8, 3, '2026-06-02T12:00:00Z');
insert into public.posts (id, campaign_id, theme, position, body, linkedin_url, status, scheduled_at, posted_at)
values ('919f6f88-61e4-4d4a-a47d-52f9628c87ad', '002dc3bc-983b-4153-9759-6fd8e6200887', 'Hiring for a wellness company is very different', 9, '', 'https://www.linkedin.com/posts/mykyta-shevchenko-ciphercross_hiring-for-a-wellness-company-is-very-different-activity-7447874698253766656-jpBB?utm_source=share&utm_medium=member_desktop&rcm=ACoAAD1GaXQBLC3IwzuWDrLQoIsrw5Y1tC2y1Xs', 'posted', '2026-04-09T09:00:00Z', '2026-04-09T09:00:00Z');
insert into public.post_stats (post_id, views, likes, comments, recorded_at)
values ('919f6f88-61e4-4d4a-a47d-52f9628c87ad', 347, 6, 0, '2026-06-02T12:00:00Z');
insert into public.posts (id, campaign_id, theme, position, body, linkedin_url, status, scheduled_at, posted_at)
values ('fa4ba77e-03c0-4457-bb70-8cc08ea4503a', '002dc3bc-983b-4153-9759-6fd8e6200887', 'Some of the most important decisions ive', 10, '', 'https://www.linkedin.com/posts/mykyta-shevchenko-ciphercross_some-of-the-most-important-decisions-ive-activity-7449335686731554816-UIVD?utm_source=share&utm_medium=member_desktop&rcm=ACoAAD1GaXQBLC3IwzuWDrLQoIsrw5Y1tC2y1Xs', 'posted', '2026-04-13T09:00:00Z', '2026-04-13T09:00:00Z');
insert into public.post_stats (post_id, views, likes, comments, recorded_at)
values ('fa4ba77e-03c0-4457-bb70-8cc08ea4503a', 175, 3, 0, '2026-06-02T12:00:00Z');
insert into public.posts (id, campaign_id, theme, position, body, linkedin_url, status, scheduled_at, posted_at)
values ('00947693-9328-45dc-987e-5fe5e54cb8b2', '002dc3bc-983b-4153-9759-6fd8e6200887', 'When you build for mental health engagement', 11, '', 'https://www.linkedin.com/posts/mykyta-shevchenko-ciphercross_when-you-build-for-mental-health-engagement-activity-7449867830109442052-whqX?utm_source=share&utm_medium=member_desktop&rcm=ACoAAD1GaXQBLC3IwzuWDrLQoIsrw5Y1tC2y1Xs', 'posted', '2026-04-14T09:00:00Z', '2026-04-14T09:00:00Z');
insert into public.post_stats (post_id, views, likes, comments, recorded_at)
values ('00947693-9328-45dc-987e-5fe5e54cb8b2', 242, 10, 0, '2026-06-02T12:00:00Z');
insert into public.posts (id, campaign_id, theme, position, body, linkedin_url, status, scheduled_at, posted_at)
values ('860fcf2c-eef6-4a58-b75b-f64a825a9b1d', '002dc3bc-983b-4153-9759-6fd8e6200887', 'Wellness tech is growing fast but not all', 12, '', 'https://www.linkedin.com/posts/mykyta-shevchenko-ciphercross_wellness-tech-is-growing-fast-but-not-all-activity-7452408334432862208-ByjF?utm_source=share&utm_medium=member_desktop&rcm=ACoAAD1GaXQBLC3IwzuWDrLQoIsrw5Y1tC2y1Xs', 'posted', '2026-04-21T09:00:00Z', '2026-04-21T09:00:00Z');
insert into public.post_stats (post_id, views, likes, comments, recorded_at)
values ('860fcf2c-eef6-4a58-b75b-f64a825a9b1d', 184, 5, 0, '2026-06-02T12:00:00Z');
insert into public.posts (id, campaign_id, theme, position, body, linkedin_url, status, scheduled_at, posted_at)
values ('79b4f69b-0217-47a6-9cb0-23c294f2df48', '002dc3bc-983b-4153-9759-6fd8e6200887', 'Why trust is the core product', 13, '', 'https://www.linkedin.com/posts/mykyta-shevchenko-ciphercross_why-trust-is-the-core-product-activity-7452623494145638400-PCZv?utm_source=share&utm_medium=member_desktop&rcm=ACoAAD1GaXQBLC3IwzuWDrLQoIsrw5Y1tC2y1Xs', 'posted', '2026-04-22T09:00:00Z', '2026-04-22T09:00:00Z');
insert into public.post_stats (post_id, views, likes, comments, recorded_at)
values ('79b4f69b-0217-47a6-9cb0-23c294f2df48', 244, 3, 0, '2026-06-02T12:00:00Z');
insert into public.posts (id, campaign_id, theme, position, body, linkedin_url, status, scheduled_at, posted_at)
values ('1d30e3e1-89f1-4281-851a-3ad87db03f2f', '002dc3bc-983b-4153-9759-6fd8e6200887', 'I didnt expect overthinking to become part', 14, '', 'https://www.linkedin.com/posts/mykyta-shevchenko-ciphercross_i-didnt-expect-overthinking-to-become-part-activity-7452963265938087936-9IU1?utm_source=share&utm_medium=member_desktop&rcm=ACoAAD1GaXQBLC3IwzuWDrLQoIsrw5Y1tC2y1Xs', 'posted', '2026-04-23T09:00:00Z', '2026-04-23T09:00:00Z');
insert into public.post_stats (post_id, views, likes, comments, recorded_at)
values ('1d30e3e1-89f1-4281-851a-3ad87db03f2f', 121, 7, 0, '2026-06-02T12:00:00Z');
insert into public.posts (id, campaign_id, theme, position, body, linkedin_url, status, scheduled_at, posted_at)
values ('36e1c86e-ac96-4d54-aba1-aa1a1dab8cb0', '002dc3bc-983b-4153-9759-6fd8e6200887', 'I didnt understand what wellness really', 15, '', 'https://www.linkedin.com/posts/mykyta-shevchenko-ciphercross_i-didnt-understand-what-wellness-really-activity-7454778960221138944-y75Q?utm_source=share&utm_medium=member_desktop&rcm=ACoAAD1GaXQBLC3IwzuWDrLQoIsrw5Y1tC2y1Xs', 'posted', '2026-04-28T09:00:00Z', '2026-04-28T09:00:00Z');
insert into public.post_stats (post_id, views, likes, comments, recorded_at)
values ('36e1c86e-ac96-4d54-aba1-aa1a1dab8cb0', 162, 5, 5, '2026-06-02T12:00:00Z');
insert into public.posts (id, campaign_id, theme, position, body, linkedin_url, status, scheduled_at, posted_at)
values ('43d98104-7301-49f2-8c76-4223590e1ee9', '002dc3bc-983b-4153-9759-6fd8e6200887', 'A quick mvp in wellness saas or healthtech', 16, '', 'https://www.linkedin.com/posts/mykyta-shevchenko-ciphercross_a-quick-mvp-in-wellness-saas-or-healthtech-activity-7455149530045427712-e2Rf?utm_source=share&utm_medium=member_desktop&rcm=ACoAAD1GaXQBLC3IwzuWDrLQoIsrw5Y1tC2y1Xs', 'posted', '2026-04-29T09:00:00Z', '2026-04-29T09:00:00Z');
insert into public.post_stats (post_id, views, likes, comments, recorded_at)
values ('43d98104-7301-49f2-8c76-4223590e1ee9', 151, 6, 0, '2026-06-02T12:00:00Z');
insert into public.posts (id, campaign_id, theme, position, body, linkedin_url, status, scheduled_at, posted_at)
values ('1f925f22-4e99-4922-92e4-0ea72fcef9f9', '002dc3bc-983b-4153-9759-6fd8e6200887', 'Anyone else or just me', 17, '', 'https://www.linkedin.com/posts/mykyta-shevchenko-ciphercross_anyone-else-or-just-me-activity-7455522585808760832-8ekd?utm_source=share&utm_medium=member_desktop&rcm=ACoAAD1GaXQBLC3IwzuWDrLQoIsrw5Y1tC2y1Xs', 'posted', '2026-04-30T09:00:00Z', '2026-04-30T09:00:00Z');
insert into public.post_stats (post_id, views, likes, comments, recorded_at)
values ('1f925f22-4e99-4922-92e4-0ea72fcef9f9', 395, 5, 0, '2026-06-02T12:00:00Z');
insert into public.posts (id, campaign_id, theme, position, body, linkedin_url, status, scheduled_at, posted_at)
values ('85e7c616-eece-4f97-b05b-77cc690e6b03', '002dc3bc-983b-4153-9759-6fd8e6200887', 'LI Company Post — 2026-04-30', 18, '', 'https://www.linkedin.com/feed/update/urn:li:activity:7455526642459869184', 'posted', '2026-04-30T09:00:00Z', '2026-04-30T09:00:00Z');
insert into public.post_stats (post_id, views, likes, comments, recorded_at)
values ('85e7c616-eece-4f97-b05b-77cc690e6b03', 67, 1, 0, '2026-06-02T12:00:00Z');
insert into public.posts (id, campaign_id, theme, position, body, linkedin_url, status, scheduled_at, posted_at)
values ('2f24368b-df15-4e08-bf8f-9761c06487b3', '7457514f-ff06-4512-8726-3b980ef6e90f', 'LI Company Post — 2026-03-19', 0, '', 'https://www.linkedin.com/feed/update/urn:li:activity:7440309818780880897', 'posted', '2026-03-19T09:00:00Z', '2026-03-19T09:00:00Z');
insert into public.post_stats (post_id, views, likes, comments, recorded_at)
values ('2f24368b-df15-4e08-bf8f-9761c06487b3', 93, 1, 0, '2026-06-02T12:00:00Z');
insert into public.posts (id, campaign_id, theme, position, body, linkedin_url, status, scheduled_at, posted_at)
values ('7b3f9b43-b509-451e-8281-a5e8cae31751', '7457514f-ff06-4512-8726-3b980ef6e90f', 'LI Useful Post — 2026-03-23', 1, '', 'https://www.linkedin.com/feed/update/urn:li:activity:7441755748641968128', 'posted', '2026-03-23T09:00:00Z', '2026-03-23T09:00:00Z');
insert into public.post_stats (post_id, views, likes, comments, recorded_at)
values ('7b3f9b43-b509-451e-8281-a5e8cae31751', 62, 2, 0, '2026-06-02T12:00:00Z');
insert into public.posts (id, campaign_id, theme, position, body, linkedin_url, status, scheduled_at, posted_at)
values ('98d1f746-c2f6-474e-968e-827144d92197', '7457514f-ff06-4512-8726-3b980ef6e90f', 'LI Useful Post — 2026-03-25', 2, '', 'https://www.linkedin.com/feed/update/urn:li:activity:7442472954174570496', 'posted', '2026-03-25T09:00:00Z', '2026-03-25T09:00:00Z');
insert into public.post_stats (post_id, views, likes, comments, recorded_at)
values ('98d1f746-c2f6-474e-968e-827144d92197', 126, 2, 1, '2026-06-02T12:00:00Z');
insert into public.posts (id, campaign_id, theme, position, body, linkedin_url, status, scheduled_at, posted_at)
values ('418e4f2a-e63c-4fb2-be83-5d6b035e5e96', '7457514f-ff06-4512-8726-3b980ef6e90f', 'LI Useful Post — 2026-03-26', 3, '', 'https://www.linkedin.com/feed/update/urn:li:activity:7442843168993226752', 'posted', '2026-03-26T09:00:00Z', '2026-03-26T09:00:00Z');
insert into public.post_stats (post_id, views, likes, comments, recorded_at)
values ('418e4f2a-e63c-4fb2-be83-5d6b035e5e96', 78, 4, 0, '2026-06-02T12:00:00Z');
insert into public.posts (id, campaign_id, theme, position, body, linkedin_url, status, scheduled_at, posted_at)
values ('9f237dce-7e96-440b-ae3c-fbfc787d9c08', '7457514f-ff06-4512-8726-3b980ef6e90f', 'LI Case Post — 2026-03-30', 4, '', 'https://www.linkedin.com/feed/update/urn:li:activity:7444269754137067520', 'posted', '2026-03-30T09:00:00Z', '2026-03-30T09:00:00Z');
insert into public.post_stats (post_id, views, likes, comments, recorded_at)
values ('9f237dce-7e96-440b-ae3c-fbfc787d9c08', 101, 3, 0, '2026-06-02T12:00:00Z');
insert into public.posts (id, campaign_id, theme, position, body, linkedin_url, status, scheduled_at, posted_at)
values ('afd0aff1-64e8-4a51-ba7f-0990352425d0', '7457514f-ff06-4512-8726-3b980ef6e90f', 'LI Case Post — 2026-04-01', 5, '', 'https://www.linkedin.com/feed/update/urn:li:activity:7445005820708245505', 'posted', '2026-04-01T09:00:00Z', '2026-04-01T09:00:00Z');
insert into public.post_stats (post_id, views, likes, comments, recorded_at)
values ('afd0aff1-64e8-4a51-ba7f-0990352425d0', 36, 2, 0, '2026-06-02T12:00:00Z');
insert into public.posts (id, campaign_id, theme, position, body, linkedin_url, status, scheduled_at, posted_at)
values ('6ce0b4e2-da62-4b0a-9164-fa6c8c3396f9', '7457514f-ff06-4512-8726-3b980ef6e90f', 'LI Team Post — 2026-04-02', 6, '', 'https://www.linkedin.com/feed/update/urn:li:activity:7445360679953338368', 'posted', '2026-04-02T09:00:00Z', '2026-04-02T09:00:00Z');
insert into public.post_stats (post_id, views, likes, comments, recorded_at)
values ('6ce0b4e2-da62-4b0a-9164-fa6c8c3396f9', 45, 2, 0, '2026-06-02T12:00:00Z');
insert into public.posts (id, campaign_id, theme, position, body, linkedin_url, status, scheduled_at, posted_at)
values ('6d28cbf6-026c-4fde-af94-09718682b6c2', '7457514f-ff06-4512-8726-3b980ef6e90f', 'LI Useful Post — 2026-04-06', 7, '', 'https://www.linkedin.com/feed/update/urn:li:activity:7446802628681912320', 'posted', '2026-04-06T09:00:00Z', '2026-04-06T09:00:00Z');
insert into public.post_stats (post_id, views, likes, comments, recorded_at)
values ('6d28cbf6-026c-4fde-af94-09718682b6c2', 61, 2, 0, '2026-06-02T12:00:00Z');
insert into public.posts (id, campaign_id, theme, position, body, linkedin_url, status, scheduled_at, posted_at)
values ('7400ace5-1872-43b5-8690-3d9c32677ba6', '7457514f-ff06-4512-8726-3b980ef6e90f', 'LI Useful Post — 2026-04-07', 8, '', 'https://www.linkedin.com/feed/update/urn:li:activity:7447172617129652224', 'posted', '2026-04-07T09:00:00Z', '2026-04-07T09:00:00Z');
insert into public.post_stats (post_id, views, likes, comments, recorded_at)
values ('7400ace5-1872-43b5-8690-3d9c32677ba6', 62, 2, 0, '2026-06-02T12:00:00Z');
insert into public.posts (id, campaign_id, theme, position, body, linkedin_url, status, scheduled_at, posted_at)
values ('4b24bfb5-1561-4fbe-8ea9-0d583b43fb14', '7457514f-ff06-4512-8726-3b980ef6e90f', 'LI Useful Post — 2026-04-09', 9, '', 'https://www.linkedin.com/feed/update/urn:li:activity:7447878494262431744', 'posted', '2026-04-09T09:00:00Z', '2026-04-09T09:00:00Z');
insert into public.post_stats (post_id, views, likes, comments, recorded_at)
values ('4b24bfb5-1561-4fbe-8ea9-0d583b43fb14', 31, 1, 0, '2026-06-02T12:00:00Z');
insert into public.posts (id, campaign_id, theme, position, body, linkedin_url, status, scheduled_at, posted_at)
values ('2b481fc4-369d-4575-b4fc-ec88eea9ea84', '7457514f-ff06-4512-8726-3b980ef6e90f', 'LI Company Post — 2026-04-13', 10, '', 'https://www.linkedin.com/feed/update/urn:li:activity:7449331805339402240', 'posted', '2026-04-13T09:00:00Z', '2026-04-13T09:00:00Z');
insert into public.post_stats (post_id, views, likes, comments, recorded_at)
values ('2b481fc4-369d-4575-b4fc-ec88eea9ea84', 57, 2, 0, '2026-06-02T12:00:00Z');
insert into public.posts (id, campaign_id, theme, position, body, linkedin_url, status, scheduled_at, posted_at)
values ('943e5ab7-c4e8-463f-b9e0-cef1b6a2091a', '7457514f-ff06-4512-8726-3b980ef6e90f', 'LI Useful Post — 2026-04-14', 11, '', 'https://www.linkedin.com/feed/update/urn:li:activity:7449713166818623488', 'posted', '2026-04-14T09:00:00Z', '2026-04-14T09:00:00Z');
insert into public.post_stats (post_id, views, likes, comments, recorded_at)
values ('943e5ab7-c4e8-463f-b9e0-cef1b6a2091a', 42, 2, 0, '2026-06-02T12:00:00Z');
insert into public.posts (id, campaign_id, theme, position, body, linkedin_url, status, scheduled_at, posted_at)
values ('dd838278-2caf-493f-8475-0eb1dcc30397', '7457514f-ff06-4512-8726-3b980ef6e90f', 'LI Team Post — 2026-04-16', 12, '', 'https://www.linkedin.com/feed/update/urn:li:activity:7450434088420798464', 'posted', '2026-04-16T09:00:00Z', '2026-04-16T09:00:00Z');
insert into public.post_stats (post_id, views, likes, comments, recorded_at)
values ('dd838278-2caf-493f-8475-0eb1dcc30397', 59, 1, 0, '2026-06-02T12:00:00Z');
insert into public.posts (id, campaign_id, theme, position, body, linkedin_url, status, scheduled_at, posted_at)
values ('8c01d4f4-99ad-49db-b831-f2f7b72a8712', '7457514f-ff06-4512-8726-3b980ef6e90f', 'LI Case Post — 2026-04-21', 13, '', 'https://www.linkedin.com/feed/update/urn:li:activity:7452250266281746432', 'posted', '2026-04-21T09:00:00Z', '2026-04-21T09:00:00Z');
insert into public.post_stats (post_id, views, likes, comments, recorded_at)
values ('8c01d4f4-99ad-49db-b831-f2f7b72a8712', 77, 3, 0, '2026-06-02T12:00:00Z');
insert into public.posts (id, campaign_id, theme, position, body, linkedin_url, status, scheduled_at, posted_at)
values ('a1dd056c-0140-494d-9135-9a3e7c8dcc9b', '7457514f-ff06-4512-8726-3b980ef6e90f', 'LI Company Post — 2026-04-22', 14, '', 'https://www.linkedin.com/feed/update/urn:li:activity:7452604663218163712', 'posted', '2026-04-22T09:00:00Z', '2026-04-22T09:00:00Z');
insert into public.post_stats (post_id, views, likes, comments, recorded_at)
values ('a1dd056c-0140-494d-9135-9a3e7c8dcc9b', 78, 2, 0, '2026-06-02T12:00:00Z');
insert into public.posts (id, campaign_id, theme, position, body, linkedin_url, status, scheduled_at, posted_at)
values ('45e1ff12-cf77-4482-90e1-aba83ea968f7', '7457514f-ff06-4512-8726-3b980ef6e90f', 'LI Useful Post — 2026-04-23', 15, '', 'https://www.linkedin.com/feed/update/urn:li:activity:7453102947208540160', 'posted', '2026-04-23T09:00:00Z', '2026-04-23T09:00:00Z');
insert into public.post_stats (post_id, views, likes, comments, recorded_at)
values ('45e1ff12-cf77-4482-90e1-aba83ea968f7', 73, 2, 0, '2026-06-02T12:00:00Z');
insert into public.posts (id, campaign_id, theme, position, body, linkedin_url, status, scheduled_at, posted_at)
values ('2b1b810e-c531-40cd-94c8-05b2fed3c402', '7457514f-ff06-4512-8726-3b980ef6e90f', 'LI Case Post — 2026-04-28', 16, '', 'https://www.linkedin.com/feed/update/urn:li:activity:7454794112073101312', 'posted', '2026-04-28T09:00:00Z', '2026-04-28T09:00:00Z');
insert into public.post_stats (post_id, views, likes, comments, recorded_at)
values ('2b1b810e-c531-40cd-94c8-05b2fed3c402', 38, 0, 0, '2026-06-02T12:00:00Z');
insert into public.posts (id, campaign_id, theme, position, body, linkedin_url, status, scheduled_at, posted_at)
values ('17dd8a86-3e0d-4bce-b892-9f64596c168e', '7457514f-ff06-4512-8726-3b980ef6e90f', 'LI Company Post — 2026-04-29', 17, '', 'https://www.linkedin.com/feed/update/urn:li:activity:7455133779444289536', 'posted', '2026-04-29T09:00:00Z', '2026-04-29T09:00:00Z');
insert into public.post_stats (post_id, views, likes, comments, recorded_at)
values ('17dd8a86-3e0d-4bce-b892-9f64596c168e', 52, 2, 0, '2026-06-02T12:00:00Z');

commit;
